# Image folder script parser
# parses image folder(s) to generate Image object declarations
# move generated file to Data folder as this file is the 2nd part of the SeedData class
import os,sys

def GetName(file):
    return os.path.splitext(file)[0].capitalize().replace("_","")

def WriteDecl(folder, i):
    files = os.listdir(folder)
    for file in files:
        output.write('\t\t\timages.Add(new Image {{ ID = {3}, Source = "/images/{2}/{0}", ImageName = "{1}", Category = "None", ReferenceCount = 0 }});\n'.format(file, GetName(file),folder,i))
        i += 1
    return i

output = open("AutogenImageList.cs","w")

output.write("using System.Collections.Generic;\n"+
             "using BoardProject.Models;\n\n"+
             "namespace BoardProject.Data\n{\n"+
             "\tpublic static partial class SeedData\n\t{\n"+
             "\t\t/* Autogenerated file by parse_file.py */\n"+
             "\t\tprivate static List<Image> AutogenList()\n\t\t{\n"+
             "\t\t\tList<Image> images = new List<Image>();\n\n")
i = 7
if (len(sys.argv) == 1):
    # single file path
    folder = input("Please type the name of the folder: ")
    WriteDecl(folder,i)
else:
    # multiple file path
    folders = sys.argv[1::]
    for folder in folders:
        i = WriteDecl(folder,i)
        
output.write("\n\t\t\treturn images;\n\t\t}\n\t}\n}\n")
output.close()
