using System.Collections.Generic;
using System.Linq;
using BoardProject.Models;

namespace BoardProject.Data
{
    public static class SeedData
    {
        public static void PutTestData()
        {
            using DataContext DBConnection = new DataContext();

            if (DBConnection.UserData.Any() ||
                DBConnection.BoardData.Any() ||
                DBConnection.TileData.Any() ||
                DBConnection.Image.Any())
            {
                return;
            }
            UserData TestUser = new UserData {
                Username = "TestUser",
                PasswordHash = "1111",
                PasswordSalt = "1111",
                IsPrimary = true,
                IsManager = false,
                Font = "Comic Sans",
                FontSize = 200.0,
                BackgroundColor = 0x800080,
                TextColor = 0xFF0000,
                DPI = 110,
                BoardIDs = "1;2;",
                HomeBoardID = "1"
            };
            DBConnection.UserData.Add(TestUser);
            BoardData TestBoard = new BoardData {
                BoardName = "TestBoard",
                BoardHeader = "Test Header",
                TileIDs = "1;2;3;4;5;6;",
                BackgroundColor = 0xFFFFFF,
                TextColor = 0x000080,
                FontSize = 100.0
            };
            DBConnection.BoardData.Add(TestBoard);
            List<TileData> TestTiles = new List<TileData>
            {
                new TileData { TileName = "TestTile1", TileText = "Test1", BackgroundColor = 0xFF0000, SourceID = 1 },
                new TileData { TileName = "TestTile2", TileText = "Test2", BackgroundColor = 0x0000FF, SourceID = 2 },
                new TileData { TileName = "TestTile3", TileText = "Test3", BackgroundColor = 0x00FF00, SourceID = 3 },
                new TileData { TileName = "TestTile4", TileText = "Test4", BackgroundColor = 0xFFFF00, SourceID = 4 },
                new TileData { TileName = "TestTile5", TileText = "Test5", BackgroundColor = 0xFFFFFF, SourceID = 5 },
                new TileData { TileName = "TestTile6", TileText = "Test6", BackgroundColor = 0x000000, SourceID = 6 }
            };
            DBConnection.TileData.AddRange(TestTiles);
            List<Image> TestImages = new List<Image>
            {
                new Image { Source = "/images/test1.jpg", ImageName = "TestImage1", Category = "No Category", ReferenceCount = 0},
                new Image { Source = "/images/test2.gif", ImageName = "TestImage2", Category = "No Category", ReferenceCount = 0},
                new Image { Source = "/images/test3.jpg", ImageName = "TestImage3", Category = "No Category", ReferenceCount = 0},
                new Image { Source = "/images/test4.jpg", ImageName = "TestImage4", Category = "No Category", ReferenceCount = 0},
                new Image { Source = "/images/test5.jpg", ImageName = "TestImage5", Category = "No Category", ReferenceCount = 0},
                new Image { Source = "/images/test6.jpg", ImageName = "TestImage6", Category = "No Category", ReferenceCount = 0}
            };
            DBConnection.Image.AddRange(TestImages);
            DBConnection.SaveChanges();

            /* Add ARASAAC-sourced pictograms */
            List<Image> NewImages = new List<Image>();
            List<TileData> NewTiles = new List<TileData>();
            /* Autogenerated object declarations (by parse_files.py) */
            {
                NewImages.Add(new Image { ID = 7, Source = "/images/pictograms/1.png", ImageName = "1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 8, Source = "/images/pictograms/1_1.png", ImageName = "11", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 9, Source = "/images/pictograms/1_2.png", ImageName = "12", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 10, Source = "/images/pictograms/2.png", ImageName = "2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 11, Source = "/images/pictograms/2_1.png", ImageName = "21", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 12, Source = "/images/pictograms/3.png", ImageName = "3", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 13, Source = "/images/pictograms/3_1.png", ImageName = "31", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 14, Source = "/images/pictograms/4.png", ImageName = "4", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 15, Source = "/images/pictograms/6.png", ImageName = "6", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 16, Source = "/images/pictograms/6_1.png", ImageName = "61", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 17, Source = "/images/pictograms/7.png", ImageName = "7", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 18, Source = "/images/pictograms/7_1.png", ImageName = "71", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 19, Source = "/images/pictograms/8.png", ImageName = "8", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 20, Source = "/images/pictograms/8_1.png", ImageName = "81", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 21, Source = "/images/pictograms/9.png", ImageName = "9", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 22, Source = "/images/pictograms/9_1.png", ImageName = "91", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 23, Source = "/images/pictograms/absent-minded.png", ImageName = "Absent-minded", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 24, Source = "/images/pictograms/act.png", ImageName = "Act", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 25, Source = "/images/pictograms/adapted library.png", ImageName = "Adapted library", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 26, Source = "/images/pictograms/adapted sinks.png", ImageName = "Adapted sinks", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 27, Source = "/images/pictograms/adapted washbasins.png", ImageName = "Adapted washbasins", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 28, Source = "/images/pictograms/aeroplane.png", ImageName = "Aeroplane", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 29, Source = "/images/pictograms/aeroplanes.png", ImageName = "Aeroplanes", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 30, Source = "/images/pictograms/age.png", ImageName = "Age", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 31, Source = "/images/pictograms/airplanes.png", ImageName = "Airplanes", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 32, Source = "/images/pictograms/airport.png", ImageName = "Airport", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 33, Source = "/images/pictograms/angry.png", ImageName = "Angry", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 34, Source = "/images/pictograms/angry_1.png", ImageName = "Angry1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 35, Source = "/images/pictograms/angry_2.png", ImageName = "Angry2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 36, Source = "/images/pictograms/angry_3.png", ImageName = "Angry3", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 37, Source = "/images/pictograms/annoying.png", ImageName = "Annoying", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 38, Source = "/images/pictograms/bad.png", ImageName = "Bad", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 39, Source = "/images/pictograms/bad_1.png", ImageName = "Bad1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 40, Source = "/images/pictograms/balloon.png", ImageName = "Balloon", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 41, Source = "/images/pictograms/basket ball.png", ImageName = "Basket ball", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 42, Source = "/images/pictograms/bass drum.png", ImageName = "Bass drum", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 43, Source = "/images/pictograms/be thirsty.png", ImageName = "Be thirsty", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 44, Source = "/images/pictograms/be thirsty_1.png", ImageName = "Be thirsty1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 45, Source = "/images/pictograms/bear.png", ImageName = "Bear", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 46, Source = "/images/pictograms/bear_1.png", ImageName = "Bear1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 47, Source = "/images/pictograms/bee.png", ImageName = "Bee", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 48, Source = "/images/pictograms/bird.png", ImageName = "Bird", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 49, Source = "/images/pictograms/bite.png", ImageName = "Bite", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 50, Source = "/images/pictograms/bite_1.png", ImageName = "Bite1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 51, Source = "/images/pictograms/bite_2.png", ImageName = "Bite2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 52, Source = "/images/pictograms/blind.png", ImageName = "Blind", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 53, Source = "/images/pictograms/blind_1.png", ImageName = "Blind1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 54, Source = "/images/pictograms/blind_2.png", ImageName = "Blind2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 55, Source = "/images/pictograms/boring.png", ImageName = "Boring", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 56, Source = "/images/pictograms/bowling.png", ImageName = "Bowling", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 57, Source = "/images/pictograms/brushed.png", ImageName = "Brushed", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 58, Source = "/images/pictograms/bundle of nerves.png", ImageName = "Bundle of nerves", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 59, Source = "/images/pictograms/butterfly.png", ImageName = "Butterfly", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 60, Source = "/images/pictograms/canteens.png", ImageName = "Canteens", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 61, Source = "/images/pictograms/car.png", ImageName = "Car", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 62, Source = "/images/pictograms/cards.png", ImageName = "Cards", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 63, Source = "/images/pictograms/car_1.png", ImageName = "Car1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 64, Source = "/images/pictograms/car_2.png", ImageName = "Car2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 65, Source = "/images/pictograms/car_3.png", ImageName = "Car3", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 66, Source = "/images/pictograms/cat.png", ImageName = "Cat", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 67, Source = "/images/pictograms/celebrations.png", ImageName = "Celebrations", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 68, Source = "/images/pictograms/ceremonies.png", ImageName = "Ceremonies", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 69, Source = "/images/pictograms/chauffeur.png", ImageName = "Chauffeur", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 70, Source = "/images/pictograms/chess.png", ImageName = "Chess", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 71, Source = "/images/pictograms/chicken.png", ImageName = "Chicken", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 72, Source = "/images/pictograms/Cinderella.png", ImageName = "Cinderella", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 73, Source = "/images/pictograms/cold.png", ImageName = "Cold", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 74, Source = "/images/pictograms/comic.png", ImageName = "Comic", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 75, Source = "/images/pictograms/comic_1.png", ImageName = "Comic1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 76, Source = "/images/pictograms/computer labs.png", ImageName = "Computer labs", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 77, Source = "/images/pictograms/computer labs_1.png", ImageName = "Computer labs1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 78, Source = "/images/pictograms/computer room.png", ImageName = "Computer room", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 79, Source = "/images/pictograms/condolence.png", ImageName = "Condolence", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 80, Source = "/images/pictograms/content.png", ImageName = "Content", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 81, Source = "/images/pictograms/content_1.png", ImageName = "Content1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 82, Source = "/images/pictograms/content_2.png", ImageName = "Content2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 83, Source = "/images/pictograms/crocodile.png", ImageName = "Crocodile", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 84, Source = "/images/pictograms/deck of cards.png", ImageName = "Deck of cards", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 85, Source = "/images/pictograms/deck.png", ImageName = "Deck", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 86, Source = "/images/pictograms/diary.png", ImageName = "Diary", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 87, Source = "/images/pictograms/dining rooms.png", ImageName = "Dining rooms", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 88, Source = "/images/pictograms/dinosaurs.png", ImageName = "Dinosaurs", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 89, Source = "/images/pictograms/disgust.png", ImageName = "Disgust", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 90, Source = "/images/pictograms/dishevelled.png", ImageName = "Dishevelled", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 91, Source = "/images/pictograms/dizzy.png", ImageName = "Dizzy", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 92, Source = "/images/pictograms/dizzy_1.png", ImageName = "Dizzy1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 93, Source = "/images/pictograms/dizzy_2.png", ImageName = "Dizzy2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 94, Source = "/images/pictograms/dizzy_3.png", ImageName = "Dizzy3", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 95, Source = "/images/pictograms/dog.png", ImageName = "Dog", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 96, Source = "/images/pictograms/dog_1.png", ImageName = "Dog1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 97, Source = "/images/pictograms/dolphin.png", ImageName = "Dolphin", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 98, Source = "/images/pictograms/driver.png", ImageName = "Driver", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 99, Source = "/images/pictograms/duck.png", ImageName = "Duck", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 100, Source = "/images/pictograms/eagles.png", ImageName = "Eagles", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 101, Source = "/images/pictograms/egg boxes.png", ImageName = "Egg boxes", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 102, Source = "/images/pictograms/eight.png", ImageName = "Eight", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 103, Source = "/images/pictograms/eight_1.png", ImageName = "Eight1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 104, Source = "/images/pictograms/family touring car.png", ImageName = "Family touring car", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 105, Source = "/images/pictograms/fear.png", ImageName = "Fear", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 106, Source = "/images/pictograms/fear_1.png", ImageName = "Fear1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 107, Source = "/images/pictograms/find.png", ImageName = "Find", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 108, Source = "/images/pictograms/fish.png", ImageName = "Fish", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 109, Source = "/images/pictograms/fish_1.png", ImageName = "Fish1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 110, Source = "/images/pictograms/foosball.png", ImageName = "Foosball", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 111, Source = "/images/pictograms/four.png", ImageName = "Four", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 112, Source = "/images/pictograms/galleon.png", ImageName = "Galleon", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 113, Source = "/images/pictograms/go to the bathroom.png", ImageName = "Go to the bathroom", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 114, Source = "/images/pictograms/good.png", ImageName = "Good", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 115, Source = "/images/pictograms/greet.png", ImageName = "Greet", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 116, Source = "/images/pictograms/greeting.png", ImageName = "Greeting", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 117, Source = "/images/pictograms/Happy Birthday!.png", ImageName = "Happy birthday!", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 118, Source = "/images/pictograms/Happy Birthday.png", ImageName = "Happy birthday", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 119, Source = "/images/pictograms/happy.png", ImageName = "Happy", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 120, Source = "/images/pictograms/happy_1.png", ImageName = "Happy1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 121, Source = "/images/pictograms/happy_2.png", ImageName = "Happy2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 122, Source = "/images/pictograms/have an idea.png", ImageName = "Have an idea", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 123, Source = "/images/pictograms/hear music.png", ImageName = "Hear music", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 124, Source = "/images/pictograms/hello.png", ImageName = "Hello", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 125, Source = "/images/pictograms/high five.png", ImageName = "High five", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 126, Source = "/images/pictograms/high school.png", ImageName = "High school", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 127, Source = "/images/pictograms/hospital box.png", ImageName = "Hospital box", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 128, Source = "/images/pictograms/hospital ward.png", ImageName = "Hospital ward", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 129, Source = "/images/pictograms/hospital.png", ImageName = "Hospital", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 130, Source = "/images/pictograms/hospital_1.png", ImageName = "Hospital1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 131, Source = "/images/pictograms/hot.png", ImageName = "Hot", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 132, Source = "/images/pictograms/how old are you_.png", ImageName = "How old are you", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 133, Source = "/images/pictograms/how old.png", ImageName = "How old", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 134, Source = "/images/pictograms/hungry.png", ImageName = "Hungry", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 135, Source = "/images/pictograms/I can't understand you.png", ImageName = "I can't understand you", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 136, Source = "/images/pictograms/I do not know.png", ImageName = "I do not know", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 137, Source = "/images/pictograms/I don't know.png", ImageName = "I don't know", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 138, Source = "/images/pictograms/illustrated children's book series.png", ImageName = "Illustrated children's book series", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 139, Source = "/images/pictograms/incomprehensible.png", ImageName = "Incomprehensible", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 140, Source = "/images/pictograms/indifference.png", ImageName = "Indifference", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 141, Source = "/images/pictograms/invent.png", ImageName = "Invent", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 142, Source = "/images/pictograms/isolation.png", ImageName = "Isolation", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 143, Source = "/images/pictograms/isolation_1.png", ImageName = "Isolation1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 144, Source = "/images/pictograms/lamb.png", ImageName = "Lamb", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 145, Source = "/images/pictograms/laugh.png", ImageName = "Laugh", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 146, Source = "/images/pictograms/library.png", ImageName = "Library", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 147, Source = "/images/pictograms/light.png", ImageName = "Light", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 148, Source = "/images/pictograms/lion.png", ImageName = "Lion", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 149, Source = "/images/pictograms/listen to music.png", ImageName = "Listen to music", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 150, Source = "/images/pictograms/marriage.png", ImageName = "Marriage", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 151, Source = "/images/pictograms/marriages.png", ImageName = "Marriages", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 152, Source = "/images/pictograms/marriage_1.png", ImageName = "Marriage1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 153, Source = "/images/pictograms/misunderstand.png", ImageName = "Misunderstand", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 154, Source = "/images/pictograms/mourning.png", ImageName = "Mourning", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 155, Source = "/images/pictograms/mourning_1.png", ImageName = "Mourning1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 156, Source = "/images/pictograms/my turn.png", ImageName = "My turn", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 157, Source = "/images/pictograms/My turn_1.png", ImageName = "My turn1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 158, Source = "/images/pictograms/nerves.png", ImageName = "Nerves", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 159, Source = "/images/pictograms/nervous.png", ImageName = "Nervous", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 160, Source = "/images/pictograms/newly married couple.png", ImageName = "Newly married couple", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 161, Source = "/images/pictograms/newspaper.png", ImageName = "Newspaper", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 162, Source = "/images/pictograms/nine.png", ImageName = "Nine", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 163, Source = "/images/pictograms/nine_1.png", ImageName = "Nine1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 164, Source = "/images/pictograms/Noise is disturbing me.png", ImageName = "Noise is disturbing me", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 165, Source = "/images/pictograms/noisy.png", ImageName = "Noisy", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 166, Source = "/images/pictograms/nostalgic.png", ImageName = "Nostalgic", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 167, Source = "/images/pictograms/nostalgic_1.png", ImageName = "Nostalgic1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 168, Source = "/images/pictograms/nostalgic_2.png", ImageName = "Nostalgic2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 169, Source = "/images/pictograms/nought.png", ImageName = "Nought", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 170, Source = "/images/pictograms/numbers.png", ImageName = "Numbers", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 171, Source = "/images/pictograms/numbers_1.png", ImageName = "Numbers1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 172, Source = "/images/pictograms/one.png", ImageName = "One", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 173, Source = "/images/pictograms/one_1.png", ImageName = "One1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 174, Source = "/images/pictograms/one_2.png", ImageName = "One2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 175, Source = "/images/pictograms/panda bear.png", ImageName = "Panda bear", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 176, Source = "/images/pictograms/panda.png", ImageName = "Panda", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 177, Source = "/images/pictograms/parakeet.png", ImageName = "Parakeet", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 178, Source = "/images/pictograms/parties.png", ImageName = "Parties", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 179, Source = "/images/pictograms/pigeon.png", ImageName = "Pigeon", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 180, Source = "/images/pictograms/pigeon_1.png", ImageName = "Pigeon1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 181, Source = "/images/pictograms/pigs.png", ImageName = "Pigs", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 182, Source = "/images/pictograms/pigs_1.png", ImageName = "Pigs1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 183, Source = "/images/pictograms/pigs_2.png", ImageName = "Pigs2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 184, Source = "/images/pictograms/pigs_3.png", ImageName = "Pigs3", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 185, Source = "/images/pictograms/pigs_4.png", ImageName = "Pigs4", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 186, Source = "/images/pictograms/polling station.png", ImageName = "Polling station", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 187, Source = "/images/pictograms/post office.png", ImageName = "Post office", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 188, Source = "/images/pictograms/postal service.png", ImageName = "Postal service", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 189, Source = "/images/pictograms/pussy.png", ImageName = "Pussy", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 190, Source = "/images/pictograms/rattle.png", ImageName = "Rattle", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 191, Source = "/images/pictograms/rattle_1.png", ImageName = "Rattle1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 192, Source = "/images/pictograms/rattle_2.png", ImageName = "Rattle2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 193, Source = "/images/pictograms/rooster.png", ImageName = "Rooster", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 194, Source = "/images/pictograms/safety belts.png", ImageName = "Safety belts", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 195, Source = "/images/pictograms/salty.png", ImageName = "Salty", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 196, Source = "/images/pictograms/salutation.png", ImageName = "Salutation", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 197, Source = "/images/pictograms/school.png", ImageName = "School", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 198, Source = "/images/pictograms/school_1.png", ImageName = "School1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 199, Source = "/images/pictograms/sea turtle.png", ImageName = "Sea turtle", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 200, Source = "/images/pictograms/secondary school.png", ImageName = "Secondary school", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 201, Source = "/images/pictograms/seven.png", ImageName = "Seven", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 202, Source = "/images/pictograms/seven_1.png", ImageName = "Seven1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 203, Source = "/images/pictograms/sheep.png", ImageName = "Sheep", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 204, Source = "/images/pictograms/shopping carts.png", ImageName = "Shopping carts", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 205, Source = "/images/pictograms/shopping trolley.png", ImageName = "Shopping trolley", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 206, Source = "/images/pictograms/shopping trolleys.png", ImageName = "Shopping trolleys", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 207, Source = "/images/pictograms/showers.png", ImageName = "Showers", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 208, Source = "/images/pictograms/shy.png", ImageName = "Shy", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 209, Source = "/images/pictograms/shy_1.png", ImageName = "Shy1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 210, Source = "/images/pictograms/sitting.png", ImageName = "Sitting", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 211, Source = "/images/pictograms/sitting_1.png", ImageName = "Sitting1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 212, Source = "/images/pictograms/sitting_2.png", ImageName = "Sitting2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 213, Source = "/images/pictograms/six.png", ImageName = "Six", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 214, Source = "/images/pictograms/six_1.png", ImageName = "Six1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 215, Source = "/images/pictograms/skateboard.png", ImageName = "Skateboard", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 216, Source = "/images/pictograms/snail.png", ImageName = "Snail", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 217, Source = "/images/pictograms/Snow White.png", ImageName = "Snow white", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 218, Source = "/images/pictograms/speak on the phone.png", ImageName = "Speak on the phone", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 219, Source = "/images/pictograms/surprised.png", ImageName = "Surprised", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 220, Source = "/images/pictograms/surprised_1.png", ImageName = "Surprised1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 221, Source = "/images/pictograms/surprised_2.png", ImageName = "Surprised2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 222, Source = "/images/pictograms/sweet.png", ImageName = "Sweet", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 223, Source = "/images/pictograms/sweeten.png", ImageName = "Sweeten", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 224, Source = "/images/pictograms/table football.png", ImageName = "Table football", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 225, Source = "/images/pictograms/table soccer.png", ImageName = "Table soccer", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 226, Source = "/images/pictograms/telephones.png", ImageName = "Telephones", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 227, Source = "/images/pictograms/The Puss in Boots.png", ImageName = "The puss in boots", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 228, Source = "/images/pictograms/think.png", ImageName = "Think", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 229, Source = "/images/pictograms/thirst.png", ImageName = "Thirst", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 230, Source = "/images/pictograms/thirsty.png", ImageName = "Thirsty", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 231, Source = "/images/pictograms/thirsty_1.png", ImageName = "Thirsty1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 232, Source = "/images/pictograms/thirst_1.png", ImageName = "Thirst1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 233, Source = "/images/pictograms/thirst_2.png", ImageName = "Thirst2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 234, Source = "/images/pictograms/three.png", ImageName = "Three", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 235, Source = "/images/pictograms/three_1.png", ImageName = "Three1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 236, Source = "/images/pictograms/to be a nuisance.png", ImageName = "To be a nuisance", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 237, Source = "/images/pictograms/to be seated.png", ImageName = "To be seated", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 238, Source = "/images/pictograms/to be seated_1.png", ImageName = "To be seated1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 239, Source = "/images/pictograms/to be seated_2.png", ImageName = "To be seated2", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 240, Source = "/images/pictograms/to blow one's nose.png", ImageName = "To blow one's nose", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 241, Source = "/images/pictograms/to blow the nose.png", ImageName = "To blow the nose", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 242, Source = "/images/pictograms/to bother.png", ImageName = "To bother", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 243, Source = "/images/pictograms/to ca-ca.png", ImageName = "To ca-ca", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 244, Source = "/images/pictograms/to cover.png", ImageName = "To cover", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 245, Source = "/images/pictograms/to defecate.png", ImageName = "To defecate", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 246, Source = "/images/pictograms/to disturb.png", ImageName = "To disturb", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 247, Source = "/images/pictograms/to drink.png", ImageName = "To drink", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 248, Source = "/images/pictograms/to finish.png", ImageName = "To finish", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 249, Source = "/images/pictograms/to get upset.png", ImageName = "To get upset", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 250, Source = "/images/pictograms/to gladden.png", ImageName = "To gladden", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 251, Source = "/images/pictograms/to go in a wheelchair.png", ImageName = "To go in a wheelchair", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 252, Source = "/images/pictograms/to have a shit.png", ImageName = "To have a shit", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 253, Source = "/images/pictograms/to have.png", ImageName = "To have", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 254, Source = "/images/pictograms/to hold a wake over.png", ImageName = "To hold a wake over", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 255, Source = "/images/pictograms/to hold a wake over_1.png", ImageName = "To hold a wake over1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 256, Source = "/images/pictograms/to isolate.png", ImageName = "To isolate", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 257, Source = "/images/pictograms/to keep vigil over.png", ImageName = "To keep vigil over", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 258, Source = "/images/pictograms/to keep vigil over_1.png", ImageName = "To keep vigil over1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 259, Source = "/images/pictograms/to make happy.png", ImageName = "To make happy", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 260, Source = "/images/pictograms/to miss.png", ImageName = "To miss", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 261, Source = "/images/pictograms/to phone.png", ImageName = "To phone", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 262, Source = "/images/pictograms/to put on hearing aid.png", ImageName = "To put on hearing aid", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 263, Source = "/images/pictograms/to realise.png", ImageName = "To realise", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 264, Source = "/images/pictograms/to rejoice.png", ImageName = "To rejoice", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 265, Source = "/images/pictograms/to sing.png", ImageName = "To sing", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 266, Source = "/images/pictograms/to sit.png", ImageName = "To sit", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 267, Source = "/images/pictograms/to sweat.png", ImageName = "To sweat", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 268, Source = "/images/pictograms/to take a shit.png", ImageName = "To take a shit", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 269, Source = "/images/pictograms/to tire.png", ImageName = "To tire", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 270, Source = "/images/pictograms/to tuck in.png", ImageName = "To tuck in", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 271, Source = "/images/pictograms/to walk the horse.png", ImageName = "To walk the horse", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 272, Source = "/images/pictograms/to wheel.png", ImageName = "To wheel", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 273, Source = "/images/pictograms/tortoise.png", ImageName = "Tortoise", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 274, Source = "/images/pictograms/trolley.png", ImageName = "Trolley", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 275, Source = "/images/pictograms/trolley_1.png", ImageName = "Trolley1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 276, Source = "/images/pictograms/tuning fork.png", ImageName = "Tuning fork", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 277, Source = "/images/pictograms/turn.png", ImageName = "Turn", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 278, Source = "/images/pictograms/turtle.png", ImageName = "Turtle", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 279, Source = "/images/pictograms/two.png", ImageName = "Two", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 280, Source = "/images/pictograms/two_1.png", ImageName = "Two1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 281, Source = "/images/pictograms/wash hair.png", ImageName = "Wash hair", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 282, Source = "/images/pictograms/washbasins.png", ImageName = "Washbasins", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 283, Source = "/images/pictograms/wedding.png", ImageName = "Wedding", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 284, Source = "/images/pictograms/weddings.png", ImageName = "Weddings", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 285, Source = "/images/pictograms/wedding_1.png", ImageName = "Wedding1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 286, Source = "/images/pictograms/wicked.png", ImageName = "Wicked", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 287, Source = "/images/pictograms/wicked_1.png", ImageName = "Wicked1", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 288, Source = "/images/pictograms/wireless telephones.png", ImageName = "Wireless telephones", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 289, Source = "/images/pictograms/wood workshop.png", ImageName = "Wood workshop", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 290, Source = "/images/pictograms/workshop.png", ImageName = "Workshop", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 291, Source = "/images/pictograms/zebra.png", ImageName = "Zebra", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 292, Source = "/images/pictograms/zero sign.png", ImageName = "Zero sign", Category = "None", ReferenceCount = 0 });
                NewImages.Add(new Image { ID = 293, Source = "/images/pictograms/zero.png", ImageName = "Zero", Category = "None", ReferenceCount = 0 });
            }
            foreach (Image image in NewImages)
            {
                NewTiles.Add(new TileData { ID = image.ID,
                                            SourceID = image.ID,
                                            TileName = "ARASAAC: " + image.ImageName,
                                            TileText = image.ImageName,
                                            BackgroundColor = 0xFFFFFF });
                image.ImageName = "ARASAAC: " + image.ImageName;
            }
            /* Now use our newly generated tile objects in some sample boards */
            BoardData AnimalTest = new BoardData
            {
                BoardName = "Animal Board",
                BoardHeader = "Animal Pictograms",
                TileIDs = "291;278;179;216;66;181;144;83;",
                BackgroundColor = 0xFFFFFF,
                TextColor = 0x000080,
                FontSize = 100.0
            };
            DBConnection.BoardData.Add(AnimalTest);
            DBConnection.Image.AddRange(NewImages);
            DBConnection.TileData.AddRange(NewTiles);
            DBConnection.SaveChanges();
        }
    }
}