name: Azure Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action' 
        uses: actions/checkout@master
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
      - name: Build with dotnet
        run: dotnet build --configuration Debug
      - name: dotnet publish
        run: |
          dotnet publish --configuration Debug -o ${{env.DOTNET_ROOT}}/myapp /p:EnvironmentName=Development
      - name: Azure WebApp
        uses: azure/webapps-deploy@v1
        with: 
            app-name: team26boardviewer
            publish-profile: ${{ secrets.azureWebAppPublishProfile }}
            package: ${{env.DOTNET_ROOT}}/myapp 
